src/Entity/Account.php
<?php

namespace App\Entity;

use App\Repository\AccountRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: AccountRepository::class)]
class Account implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 50)]
    private $firstname;

    #[ORM\Column(type: 'string', length: 50)]
    private $lastname;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Entity/Listing.php
<?php

namespace App\Entity;

use App\Repository\ListingRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ListingRepository::class)]
class Listing
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'string', length: 255)]
    private $img;

    #[ORM\Column(type: 'datetime')]
    private $published_at;

    #[ORM\Column(type: 'string', length: 20)]
    private $category;

    public function __toString()
    {
        return $this->getTitle();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get the value of published_at
     */ 
    public function getPublishedAt()
    {
        return $this->published_at;
    }

    /**
     * Set the value of published_at
     *
     * @return  self
     */ 
    public function setPublishedAt($published_at)
    {
        $this->published_at = $published_at;

        return $this;
    }

    /**
     * Get the value of description
     */ 
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set the value of description
     *
     * @return  self
     */ 
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }
}

src/Entity/Test.php
<?php

namespace App\Entity;

use App\Repository\TestRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TestRepository::class)]
class Test
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }
}

src/Form/ListingType.php
<?php

namespace App\Form;

use App\Entity\Listing;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ListingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('img')
            ->add('published_at')
            ->add('category')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Listing::class,
        ]);
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Repository\ListingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FrontController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(ListingRepository $listingRepository, Request $request): Response
    {

        $listings = $listingRepository->findAll();

        return $this->render('front/index.html.twig', [
            'listings' => $listings,
        ]);
    }

    
}

src/Controller/ListingController.php
<?php

namespace App\Controller;

use App\Entity\Listing;
use App\Repository\ListingRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ListingController extends AbstractController
{
    #[Route('/listing/{id}', name: 'app_listing', methods:'GET')]
    public function index(Listing $listing): Response
    {
        return $this->render('listing/index.html.twig', [
            'listing' => $listing,
        ]);
    }

    
}

templates/_footer.html.twig
<footer class="bg-dark text-light">

    <div class="mx_auto text-center">
        <p>&copy; Augustin Petre 2022</p>
        {{ "now"|date("m/d/Y") }}
    </div>

</footer>

templates/_nav.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{path('app_home')}}">Accueil</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="">New Listing</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="">Sign up</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="">Log in</a>
            </li>
            {# <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Admin
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{path('app_artist_index')}}">Gestion Artistes</a></li>
                    <li><a class="dropdown-item" href="{{path('app_album_index')}}">Gestion Albums</a></li>
                    <li><a class="dropdown-item" href="{{path('app_music_index')}}">Gestion Musiques</a></li>
                </ul>
            </li> #}
        </ul>
    </div>
</nav>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

    </head>
    <body>
        {% include "_nav.html.twig" %}
        {% block body %}{% endblock %}
    </body>
    {% include "_footer.html.twig" %}
            {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
</html>

templates/front/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dealgames | Home{% endblock %}

{% block body %}

<div class="d-flex justify-content-around pt-5">
{% for listing in listings %}
  <div class="card">
    <div class="card-text">{{listing.id}}</div>
    <a href="{{path('app_listing', {id:listing.id})}}">
      <div class="card-body">
        <h5 class="card-title text-secondary text-center pb-2">{{ listing }}</h5>
        <p class="card-text">{{ listing.description|u.truncate(100, '...', false) }}</p>
        <p class="text-muted text-center">Posted : {{ listing.publishedAt|date('d M Y') }}</p>
      </div>
      <img class="card-img" src="{{asset('images/ps4.jpg')}}" alt="Card image">
      <p class="card-text">Category : {{listing.category}}</p>
    </a>
  </div>
{% endfor %}
</div>
  

{% endblock %}

templates/listing/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dealgames | Listing{% endblock %}

{% block body %}

<img src="{{asset('images/ps4.jpg')}}" alt="">
<h1>{{listing.title}}</h1>
<h3>{{listing.category}}</h3>
<p>{{listing.publishedAt|date('d M Y')}}</p>
<h3>Test Username</h3>
<p><a href="">Contact</a></p>
<h3>Test Description</h3>
<p>{{listing.description}}</p>

{% endblock %}